// src/views/TodoDetail.vue
<template>
  <section class="todo-detail" aria-label="Todo Details">
    <!-- Back button -->
    <button
      class="back-btn"
      @click="goBack"
      aria-label="Back to todo list"
    >
       <v-icon name="fa-arrow-left" /> Back
    </button>

    <!-- Loading -->
    <LoadingSpinner v-if="isLoading" />

    <!-- Error -->
    <div v-else-if="error" role="alert">Error loading todo</div>

    <!-- Not Found -->
    <div v-else-if="!todo" role="alert">Todo not found</div>

    <!-- Todo Details -->
    <div v-else>
      <h2>{{ todo.title }}</h2>
      <p>Status: {{ todo.completed ? "Completed" : "Pending" }}</p>
      <p>User ID: {{ todo.userId }}</p>
      <p>ID: {{ todo.id }}</p>
    </div>
  </section>
</template>

<script setup lang="ts">
import { useRoute, useRouter } from "vue-router";
import { useTodo } from "../composables/useTodos"; // Vue composable (instead of React hooks)
import LoadingSpinner from "../components/LoadingSpinner.vue";

// route + navigation
const route = useRoute();
const router = useRouter();
const id = route.params.id as string;

// query from composable
const { data: todo, isLoading, error } = useTodo(id);

// go back to previous page
function goBack() {
  router.back();
}
</script>

<style scoped>
/* migrate your old TodoDetail.css styles here */.todo-detail {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding: 2rem;
  background: #f9f9f9;
  border-radius: 8px;
  background-color: hsl(250, 45%, 18%);
}

.back-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: none;
  border: none;
  color: white;
  cursor: pointer;
  font-size: 1rem;
  align-self: flex-start;
}

.todo-detail h2 {
  margin: 0;
  color: white;
}

.todo-detail p {
  margin: 0.5rem 0;
  color: white;
}

</style>

// app/components/TodoDetail.tsx
"use client";
import React from "react";
import { useParams, useRouter } from "next/navigation";
import { useTodo } from "../hooks/useTodos";
import LoadingSpinner from "./LoadingSpinner";
import "../styles/TodoDetail.css";
import { FaArrowLeft } from "react-icons/fa";

interface Todo {
  id: number;
  title: string;
  completed: boolean;
  userId: number;
}

const TodoDetail: React.FC = () => {
  const params = useParams();
  const router = useRouter();

  const id = params?.id as string;

  const { data: todo, isLoading, error } = useTodo(id);

  if (isLoading) return <LoadingSpinner />;
  if (error) return <div role="alert">Error loading todo</div>;
  if (!todo) return <div role="alert">Todo not found</div>;

  return (
    <section className="todo-detail" aria-label="Todo Details">
      <button
        className="back-btn"
        onClick={() => router.back()}
        aria-label="Back to todo list"
      >
        <FaArrowLeft /> Back
      </button>
      <h2>{todo.title}</h2>
      <p>Status: {todo.completed ? "Completed" : "Pending"}</p>
      <p>User ID: {todo.userId}</p>
      <p>ID: {todo.id}</p>
    </section>
  );
};

export default TodoDetail;
