// src/components/TodoList.vue
<template>
  <section class="todo-list" aria-label="Todo List">
    <!-- Search & Filter -->
    <SearchFilter
      :search="search"
      @update:search="search = $event"
      :status="status"
      @update:status="status = $event"
    />

    <!-- Add Todo Button -->
    <button
      class="todo-list__add-button"
      @click="showForm = true"
      aria-label="Add new todo"
    >
      <v-icon name="fa-plus" /> Add Todo
    </button>

    <!-- Todo Form -->
    <TodoForm
      v-if="showForm"
      @submit="handleCreate"
      @cancel="showForm = false"
    />

    <!-- Todo Items -->
    <ul class="todo-list__items" role="list">
      <TodoItem
        v-for="todo in todos"
        :key="todo.id"
        :todo="todo"
        @delete="handleDelete"
      />
    </ul>

    <!-- Pagination -->
    <Pagination
      v-model:page="page"
      :has-more="total > page * 10"
      :total="total"
    />
  </section>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import {
  useTodos,
  useCreateTodo,
  useDeleteTodo,
} from "../composables/useTodos";
import TodoItem from "./TodoItem.vue";
import Pagination from "./Pagination.vue";
import SearchFilter from "./SearchFilter.vue";
import TodoForm from "./TodoForm.vue";
import LoadingSpinner from "./LoadingSpinner.vue";

// types
import type { Todo, TodoFormValues } from "../types";

// local state
const page = ref<number>(1);
const search = ref<string>("");
const status = ref<"all" | "complete" | "incomplete">("all");
const showForm = ref<boolean>(false);

// hooks
const { data, isLoading, error } = useTodos(page, search, status);
const createTodo = useCreateTodo();
const deleteTodo = useDeleteTodo();

// derived state
const todos = computed<Todo[]>(() => data.value?.todos || []);
const total = computed<number>(() => data.value?.total || 0);

// methods
function handleCreate(values: TodoFormValues) {
  createTodo.mutate({ ...values, completed: false, userId: 1 });
  showForm.value = false;
}

function handleDelete(id: number) {
  if (window.confirm("Are you sure you want to delete this todo?")) {
    deleteTodo.mutate(id);
  }
}
</script>

<style scoped>
.todo-list {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  box-shadow: 0 9px 10px rgba(0, 0, 0, 0.1);
  background: hsl(250, 45%, 18%);
  padding: 1rem;
  padding-right: 40px;
}

.todo-list__add-button {
  background-color: hsl(250, 70%, 10%);
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 5px;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  align-self: flex-start;
}
.todo-list__add-button:hover {
  background-color: hsl(250, 35%, 20%);
}
</style>

// src/components/TodoList.tsx
import React from "react";
import { useState } from "react";
import { useTodos, useCreateTodo, useDeleteTodo } from "../hooks/useTodos";
import TodoItem from "./TodoItem";
import Pagination from "./Pagination";
import SearchFilter from "./SearchFilter";
import TodoForm from "./TodoForm";
import LoadingSpinner from "./LoadingSpinner";
import { FaPlus } from "react-icons/fa";
import "../styles/TodoList.css";
import { Todo } from "../types";

interface TodoFormValues {
  title: string;
}

const TodoList: React.FC = () => {
  const [page, setPage] = useState<number>(1);
  const [search, setSearch] = useState<string>("");
  const [status, setStatus] = useState<"all" | "complete" | "incomplete">(
    "all"
  );
  const [showForm, setShowForm] = useState<boolean>(false);

  const { data, isLoading, error } = useTodos(page, search, status);
  const todos: Todo[] = data?.todos || [];
  const total: number = data?.total || 0;

  const createTodo = useCreateTodo();
  const deleteTodo = useDeleteTodo();

  const handleCreate = (values: TodoFormValues) => {
    createTodo.mutate({ ...values, completed: false, userId: 1 });
    setShowForm(false);
  };

  const handleDelete = (id: number) => {
    if (window.confirm("Are you sure you want to delete this todo?")) {
      deleteTodo.mutate(id);
    }
  };

  if (isLoading) return <LoadingSpinner />;
  if (error) return <div role="alert">Error loading todos</div>;

  return (
    <section className="todo-list" aria-label="Todo List">
      <SearchFilter
        search={search}
        setSearch={setSearch}
        status={status}
        setStatus={setStatus}
      />
      <button
        className="todo-list__add-button"
        onClick={() => setShowForm(true)}
        aria-label="Add new todo"
      >
        <FaPlus /> Add Todo
      </button>
      {showForm && (
        <TodoForm onSubmit={handleCreate} onCancel={() => setShowForm(false)} />
      )}
      <ul className="todo-list__items" role="list">
        {todos?.map((todo) => (
          <TodoItem key={todo.id} todo={todo} onDelete={handleDelete} />
        ))}
      </ul>
      <Pagination
        page={page}
        setPage={setPage}
        hasMore={total > page * 10}
        total={total}
      />
    </section>
  );
};

export default TodoList;
